name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v0.1.6)'
        required: true
        type: string
      publish_to_marketplace:
        description: 'Publish to VS Code Marketplace'
        required: true
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build:
    name: Build and Release Extension
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install vsce
      run: npm install -g @vscode/vsce
    
    - name: Build VSIX package
      run: |
        npm run compile
        vsce package --no-dependencies
        
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./go-symbol-completion-*.vsix
        name: Release ${{ github.event.inputs.version }}
        tag_name: ${{ github.event.inputs.version }}
        draft: false
        prerelease: false
        generate_release_notes: true
         
    - name: Publish to VS Code Marketplace
      if: ${{ github.event.inputs.publish_to_marketplace == 'true' }}
      run: vsce publish -p ${{ secrets.VSCE_TOKEN }} --no-dependencies
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }} 